server:
  port: 8081

spring:
  application:
    name: to-service
  cloud:
    stream:
      bindings:
        user-service-input:
          contentType: application/json
          destination: user-service-output
          group: to-service-input
      rabbit:
        bindings:
          user-service-input:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
              binding-routing-key: user.created